## **1. Đọc dữ liệu**

In [362]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [363]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics

In [364]:
path_train = "/content/drive/MyDrive/ids_ga_ml/UNSW_NB15_training-set.csv"
path_test = "/content/drive/MyDrive/ids_ga_ml/UNSW_NB15_testing-set.csv"

In [365]:
df_train = pd.read_csv(path_train)
df_test = pd.read_csv(path_test)

In [366]:
df_train.describe()

,id,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,label
count,175341.000000,175341.000000,175341.000000,175341.000000,1.753410e+05,1.753410e+05,1.753410e+05,175341.000000,175341.000000,1.753410e+05,...,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000
mean,87671.000000,1.359389,20.298664,18.969591,8.844844e+03,1.492892e+04,9.540619e+04,179.546997,79.609567,7.345403e+07,...,5.383538,4.206255,8.729881,0.014948,0.014948,0.133066,6.955789,9.100758,0.015752,0.680622
std,50616.731112,6.480249,136.887597,110.258271,1.747656e+05,1.436542e+05,1.654010e+05,102.940011,110.506863,1.883574e+08,...,8.047104,5.783585,10.956186,0.126048,0.126048,0.701208,8.321493,10.756952,0.124516,0.466237
min,1.000000,0.000000,1.000000,0.000000,2.800000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,43836.000000,0.000008,2.000000,0.000000,1.140000e+02,0.000000e+00,3.278614e+01,62.000000,0.000000,1.305334e+04,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000
50%,87671.000000,0.001582,2.000000,2.000000,4.300000e+02,1.640000e+02,3.225807e+03,254.000000,29.000000,8.796748e+05,...,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,3.000000,4.000000,0.000000,1.000000
75%,131506.000000,0.668069,12.000000,10.000000,1.418000e+03,1.102000e+03,1.250000e+05,254.000000,252.000000,8.888889e+07,...,5.000000,3.000000,12.000000,0.000000,0.000000,0.000000,9.000000,12.000000,0.000000,1.000000
max,175341.000000,59.999989,9616.000000,10974.000000,1.296523e+07,1.465555e+07,1.000000e+06,255.000000,254.000000,5.988000e+09,...,51.000000,46.000000,65.000000,4.000000,4.000000,30.000000,60.000000,62.000000,1.000000,1.000000

In [367]:
df_test.describe()

,id,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,label
count,82332.000000,82332.000000,82332.000000,82332.000000,8.233200e+04,8.233200e+04,8.233200e+04,82332.000000,82332.000000,8.233200e+04,...,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000
mean,41166.500000,1.006756,18.666472,17.545936,7.993908e+03,1.323379e+04,8.241089e+04,180.967667,95.713003,6.454902e+07,...,4.928898,3.663011,7.456360,0.008284,0.008381,0.129743,6.468360,9.164262,0.011126,0.550600
std,23767.345519,4.710444,133.916353,115.574086,1.716423e+05,1.514715e+05,1.486204e+05,101.513358,116.667722,1.798618e+08,...,8.389545,5.915386,11.415191,0.091171,0.092485,0.638683,8.543927,11.121413,0.104891,0.497436
min,1.000000,0.000000,1.000000,0.000000,2.400000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,20583.750000,0.000008,2.000000,0.000000,1.140000e+02,0.000000e+00,2.860611e+01,62.000000,0.000000,1.120247e+04,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000
50%,41166.500000,0.014138,6.000000,2.000000,5.340000e+02,1.780000e+02,2.650177e+03,254.000000,29.000000,5.770032e+05,...,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,3.000000,5.000000,0.000000,1.000000
75%,61749.250000,0.719360,12.000000,10.000000,1.280000e+03,9.560000e+02,1.111111e+05,254.000000,252.000000,6.514286e+07,...,4.000000,3.000000,6.000000,0.000000,0.000000,0.000000,7.000000,11.000000,0.000000,1.000000
max,82332.000000,59.999989,10646.000000,11018.000000,1.435577e+07,1.465753e+07,1.000000e+06,255.000000,253.000000,5.268000e+09,...,59.000000,38.000000,63.000000,2.000000,2.000000,16.000000,60.000000,62.000000,1.000000,1.000000

## **2. Xử lý dữ liệu**

In [368]:
def min_max_scaler(data):
  scaled_dataset = (data-data.min())/(data.max()-data.min())
  return scaled_dataset

In [369]:
# prompt: tạo 1 function, đầu vào là 1 dataframe, tạo 1 biến tên cate-col để lưu trữ list là tên các cột có kiểu dữ liệu object, ròi dùng lable encode xử lý các cột đấy
from sklearn.preprocessing import LabelEncoder

# Creating a instance of label Encoder.
le = LabelEncoder()

def tranformdata(df):
  for col in df.columns:
    if df[col].dtype == 'object':

      df[col] = le.fit_transform(df[col].astype(str))
  return df

In [370]:
y_train = df_train['attack_cat']
df_train.drop(['attack_cat', 'label'], axis=1, inplace=True)

In [371]:
y_test = df_test['attack_cat']
df_test.drop(['attack_cat', 'label'], axis=1, inplace=True)

In [372]:
df_train = tranformdata(df_train)
df_train = min_max_scaler(df_train)

In [373]:
df_test = tranformdata(df_test)
df_test = min_max_scaler(df_test)

## **3. GA-Selection-Feature**

In [374]:
import random


def ga_feature_selection(X, population_size=200, generations=200):
  """
  Performs feature selection using a Genetic Algorithm for dimensionality reduction.

  Args:
    X: The input data matrix.
    population_size: The size of the population.
    generations: The number of generations.

  Returns:
    A list of selected features.
  """

  # Initialize the population with random chromosomes.
  population = [random_chromosome(len(X[0])) for _ in range(population_size)]

  # Evaluate the fitness of each chromosome in the population.
  fitness = evaluate_population(population, X)

  # Repeat for a number of generations.
  for _ in range(generations):

    # Create a new population by selecting parents and performing crossover and mutation.
    new_population = []
    for _ in range(population_size):

      # Select parents.
      parent1 = tournament_selection(population, fitness)
      parent2 = tournament_selection(population, fitness)

      # Perform crossover.
      child = crossover(parent1, parent2)

      # Perform mutation.
      child = mutate(child)

      # Add the child to the new population.
      new_population.append(child)

    # Evaluate the fitness of the new population.
    fitness = evaluate_population(new_population, X)

    # Replace the old population with the new population.
    population = new_population

  # Select the best chromosome from the population.
  best_chromosome = population[np.argmax(fitness)]

  # Return the indices of the selected features.
  selected_features = [i for i, bit in enumerate(best_chromosome) if bit == 1]

  return selected_features

def random_chromosome(n):
  """
  Creates a random chromosome.

  Args:
    n: The length of the chromosome.

  Returns:
    A list of 0s and 1s representing the chromosome.
  """

  chromosome = []
  for _ in range(n):
    chromosome.append(random.randint(0, 1))

  return chromosome
def evaluate_population(population, X):
  """
  Evaluates the fitness of each individual in the population.

  Args:
    population: A list of individuals.
    X: The input data.

  Returns:
    A list of fitness scores, where the i-th score corresponds to the i-th individual in the population.
  """
  fitness_scores = []
  for individual in population:
    fitness_score = evaluate_individual(individual, X)
    fitness_scores.append(fitness_score)
  return fitness_scores

def evaluate_individual(individual, X):
  """
  Evaluates the fitness of an individual.

  Args:
    individual: A list of 0s and 1s representing the chromosome.
    X: The input data.

  Returns:
    The fitness score of the individual.
  """
  fitness_score = calculate_fitness(individual, X)
  return fitness_score

def calculate_fitness(individual, X):
  """
  Calculates the fitness of an individual.

  Args:
    individual: A list of 0s and 1s representing the chromosome.
    X: The input data.

  Returns:
    The fitness score of the individual.
  """
  # Replace the following line with your fitness evaluation function.
  fitness_score = sum(individual)
  return fitness_score
def tournament_selection(population, fitness):
    # Select two random individuals from the population.
    candidates = random.sample(population, 2)

    # Get the fitness scores of the candidates.
    candidate_fitness = [fitness[population.index(candidate)] for candidate in candidates]

    # Get the index of the candidate with the highest fitness score.
    best_candidate_index = np.argmax(candidate_fitness)

    # Return the individual with the highest fitness score.
    return candidates[best_candidate_index]
def crossover(parent1, parent2):
  """
  Performs crossover between two parent chromosomes.

  Args:
    parent1: The first parent chromosome.
    parent2: The second parent chromosome.

  Returns:
    A new child chromosome.
  """

  # Select a random crossover point.
  crossover_point = random.randint(1, len(parent1) - 2)

  # Create the child chromosome.
  child = parent1[:crossover_point] + parent2[crossover_point:]

  return child

def mutate(chromosome):
  """
  Mutates a chromosome with a probability of 0.1.

  Args:
    chromosome: A list of 0s and 1s representing the chromosome.

  Returns:
    The mutated chromosome.
  """

  for i in range(len(chromosome)):
    if random.random() < 0.1:
      chromosome[i] = 1 if chromosome[i] == 0 else 0

  return chromosome

In [375]:
selected_features = ga_feature_selection(df_train.values)

In [376]:
print(selected_features)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 16, 17, 19, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]

In [377]:

df_selected = df_train.iloc[:, selected_features]
df_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175341 entries, 0 to 175340
Data columns (total 36 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   dur                175341 non-null  float64
 1   proto              175341 non-null  float64
 2   service            175341 non-null  float64
 3   state              175341 non-null  float64
 4   spkts              175341 non-null  float64
 5   dpkts              175341 non-null  float64
 6   sbytes             175341 non-null  float64
 7   dbytes             175341 non-null  float64
 8   rate               175341 non-null  float64
 9   sttl               175341 non-null  float64
 10  dttl               175341 non-null  float64
 11  dload              175341 non-null  float64
 12  dloss              175341 non-null  float64
 13  sinpkt             175341 non-null  float64
 14  dinpkt             175341 non-null  float64
 15  djit               175341 non-null  float64
 16  stcpb              175341 non-null  float64
 17  dtcpb              175341 non-null  float64
 18  dwin               175341 non-null  float64
 19  tcprtt             175341 non-null  float64
 20  synack             175341 non-null  float64
 21  ackdat             175341 non-null  float64
 22  dmean              175341 non-null  float64
 23  trans_depth        175341 non-null  float64
 24  response_body_len  175341 non-null  float64
 25  ct_srv_src         175341 non-null  float64
 26  ct_dst_ltm         175341 non-null  float64
 27  ct_src_dport_ltm   175341 non-null  float64
 28  ct_dst_sport_ltm   175341 non-null  float64
 29  ct_dst_src_ltm     175341 non-null  float64
 30  is_ftp_login       175341 non-null  float64
 31  ct_ftp_cmd         175341 non-null  float64
 32  ct_flw_http_mthd   175341 non-null  float64
 33  ct_src_ltm         175341 non-null  float64
 34  ct_srv_dst         175341 non-null  float64
 35  is_sm_ips_ports    175341 non-null  float64
dtypes: float64(36)
memory usage: 48.2 MB

In [378]:
cols_dropped = list(set(df_train.columns) - set(df_selected.columns))
print(cols_dropped)

['ct_state_ttl', 'smean', 'sload', 'id', 'swin', 'sjit', 'sloss']

In [379]:

df_test.drop(cols_dropped, axis=1, inplace=True)
df_train = df_selected

## **4. Model KNN, XGBOOST, SVM**

### **4.2 Tạo model**

In [380]:
# prompt: viết một hàm  mapping các giá trị trong attack cat sang thành int

def map_attack_cat(attack_cat):


  mapping = {
    'Normal': 0,
    'Generic': 1,
    'Exploits': 2,
    'Fuzzers': 3,
    'DoS': 4,
    'Reconnaissance': 5,
    'Analysis': 6,
    'Backdoor': 7,
    'Shellcode': 8,
    'Worms': 9,
  }

  return mapping.get(attack_cat, None)

y_train = y_train.apply(map_attack_cat)
y_test = y_test.apply(map_attack_cat)

In [381]:
# prompt: import thư viện, định nghĩa ra các function với biến đầu vào là X,y , function là các model:svm,knn,xgboost , đầu ra là in các chỉ số accracy và recall

import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score
from sklearn.preprocessing import LabelEncoder



def svm(X_train, X_test, y_train, y_test):
  # Split the data into training and test sets
  # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

  # Create a SVM model
  model = SVC(kernel='linear', C=1, gamma='scale', class_weight='balanced')

  # Train the model
  model.fit(X_train, y_train)

  # Predict on the test set
  y_pred = model.predict(X_test)

  # Calculate accuracy and recall
  accuracy = accuracy_score(y_test, y_pred)
  recall = recall_score(y_test, y_pred, average='weighted')

  # Return the scores
  return accuracy, recall


def knn(X_train, X_test, y_train, y_test):
  # Split the data into training and test sets
  # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

  # Create a KNN model
  model = KNeighborsClassifier(n_neighbors=10)

  # Train the model
  model.fit(X_train, y_train)

  # Predict on the test set
  y_pred = model.predict(X_test)

  # Calculate accuracy and recall
  accuracy = accuracy_score(y_test, y_pred)
  recall = recall_score(y_test, y_pred, average='weighted')

  # Return the scores
  return accuracy, recall


def xgboost(X_train, X_test, y_train, y_test):
  # le = LabelEncoder()
  # y_train = le.fit_transform(y_train)
  # y_test = le.fit_transform(y_test)
  # Split the data into training and test sets
  # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

  # Create a XGBoost model
  model = XGBClassifier( n_estimators=50, max_depth=5 )

  # Train the model
  model.fit(X_train, y_train)

  # Predict on the test set
  y_pred = model.predict(X_test)

  # Calculate accuracy and recall
  accuracy = accuracy_score(y_test, y_pred)
  recall = recall_score(y_test, y_pred, average='weighted')

  # Return the scores
  return accuracy, recall

## **5. Đánh giá**

In [ ]:
knn_acc, knn_recall = knn(df_train,df_test,y_train,y_test)
print("knn accuracy: ", knn_acc)
print("knn recall: ", knn_recall)

knn accuracy:  0.9478179730117715
knn recall:  0.9163480998425905

In [ ]:
xg_acc, xg_recall = xgboost(df_train,df_test,y_train,y_test)
print("xgboost accuracy: ", xg_acc)
print("xgboost recall: ", xg_recall)

xgboost accuracy:  0.9656904966982487
xgboost recall:  0.9098996350364964

In [ ]:
svm_acc, svm_recall = svm(df_train,df_test,y_train,y_test)
print("svm accuracy: ", svm_acc)
print("svm recall: ", svm_recall)

svm accuracy:  0.9463505926388023
svm recall:  0.934640522875817